CREATE TABLE [dbo].[Employee]
( [EmployeeId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [FirstName] VARCHAR(64) NOT NULL,
  [LastName] VARCHAR(64) NOT NULL,
  [HireDate] DATE NOT NULL DEFAULT GETDATE(),
  [IsProjectManager] BIT NOT NULL DEFAULT 0,
  CONSTRAINT [PK_Employee] PRIMARY KEY ([EmployeeId])
)