CREATE TABLE [dbo].[Post]
( [PostId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [Subject] VARCHAR(256) NOT NULL,
  [Content] NVARCHAR(MAX) NOT NULL,
  [SendDate] DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT [PK_Post] PRIMARY KEY ([PostId])
)
