CREATE TABLE [dbo].[Project]
( [ProjectID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [Name] VARCHAR(256) NOT NULL,
  [Description] VARCHAR(MAX) NOT NULL,
  [CreationDate] DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT [PK_Project] PRIMARY KEY ([ProjectID])
)
