CREATE TABLE [dbo].[User]
( [UserID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [Email] VARCHAR(320) NOT NULL,
  [Password] VARCHAR(64) NOT NULL,
  [Salt] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  CONSTRAINT [PK_User] PRIMARY KEY ([UserID])
)