CREATE TABLE [dbo].[User]
( [UserId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [Email] VARCHAR(320) NOT NULL,
  [Password] VARBINARY(32) NOT NULL,
  [Salt] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  CONSTRAINT [PK_User] PRIMARY KEY ([UserId])
)